<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SAIN</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="BepInEx" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="System.Core" />
    <Reference Include="spt-reflection" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="UnityEngine.TextRenderingModule" />
    <Reference Include="bsg.console.core" />
    <Reference Include="UnityEngine.AudioModule" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="UnityEngine.AIModule" />
    <Reference Include="DrakiaXYZ-BigBrain" />
    <Reference Include="UnityEngine.UIElementsModule" />
    <Reference Include="0Harmony" />
    <Reference Include="Comfort" />
    <Reference Include="UnityEngine.InputLegacyModule" />
    <Reference Include="Unity.Postprocessing.Runtime" />
    <Reference Include="spt-singleplayer" />
  </ItemGroup>
</Project>